baseURL = 'https://docs.markdownsite.com/'

languageCode = 'en-us'

title = 'MarkdownSite Community Docs'

theme = 'dot-hugo'
disableLanguages = []
# google analytics

googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)
# unsafe html
[markup.goldmark.renderer]

unsafe = true


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Themefisher"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own

# customize color
primary_color = "#02007e"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################
[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
name = "Github"
link = "https://github.com/symkat/MarkdownSite"

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
copyright = ""

# banner
[Languages.en.params.banner]
title = "Community Docs"
subtitle = "Documents to get up to speed on hosting your website."
bg_image = "images/banner.jpg"
placeholder = "Have a question? Just ask here or enter terms"

# call to action
[Languages.en.params.cta]
enable = true
title = "Didn't find an answer to your question?"
content = "These documents are maintained on GitHub, please open an issue or pull request."
# call to action button
[Languages.en.params.cta.button]
enable = true
label = "visit repo"
link = "https://github.com/symkat/docs.markdownsite.com"


################## english navigation #################
[[Languages.en.menu.main]]
name = "home"
url = "https://markdownsite.com"
weight = 1

[[Languages.en.menu.main]]
name = "blog"
url = "https://blog.markdownsite.com"
weight = 2

[[Languages.en.menu.main]]
name = "contact"
url = "https://markdownsite.com/contact"
weight = 3

[[Languages.en.menu.main]]
name = "docs"
url = "https://docs.markdownsite.com"
weight = 4
